function buildDestinationList() {
    $.each(cities, function(i, city) {
      destinations.push(city.city);
    });
}

buildDestinationList();

var substringMatcher = function(strs) {
          return function findMatches(q, cb) {
            var substringRegex;
 
            // an array that will be populated with substring matches
            matches = [];
 
            // regex used to determine if a string contains the substring `q`
            substrRegex = new RegExp( "^" + q, "i" );
 
            // iterate through the pool of strings and for any string that
            // contains the substring `q`, add it to the `matches` array
            $.each(strs, function(i, str) {
                //console.log(str);
                if (substrRegex.test(str)) {
                  // the typeahead jQuery plugin expects suggestions to a
                  // JavaScript object, refer to typeahead docs for more info
                  matches.push({ value: str });
                }
            });
          //console.log(matches)
          cb(matches);
          };
      };

var destinations = [];

var cities = [
    {"city": "Amsterdam", "ranking": 0},
    {"city": "Aberdeen", "ranking": 0},
    {"city": "Athens", "ranking": 0},
    {"city": "Agadir", "ranking": 0},
    {"city": "Aarhus", "ranking": 0},
    {"city": "Abu Dhabi", "ranking": 0},
    {"city": "Acapulco", "ranking": 0},
    {"city": "Adelaide", "ranking": 0},
    {"city": "Anchorage", "ranking": 0},
    {"city": "Anaheim", "ranking": 0},
    {"city": "Antalya", "ranking": 0},
    {"city": "Antwerp", "ranking": 0},
    {"city": "Atlanta", "ranking": 0},
    {"city": "Auckland", "ranking": 0},
    {"city": "Austin", "ranking": 0},
    {"city": "Berlin", "ranking": 0},
    {"city": "Bath", "ranking": 0},
    {"city": "Barcelona", "ranking": 0},
    {"city": "Belfast", "ranking": 0},
    {"city": "Birmingham, UK", "ranking": 0},
    {"city": "Bangalore", "ranking": 0},
    {"city": "Bangkok", "ranking": 0},
    {"city": "Baghdad", "ranking": 0},
    {"city": "Bari", "ranking": 0},
    {"city": "Belgrade", "ranking": 0},
    {"city": "Bern", "ranking": 0},
    {"city": "Bergen", "ranking": 0},
    {"city": "Baltimore", "ranking": 0},
    {"city": "Blackpool", "ranking": 0},
    {"city": "Bournemouth", "ranking": 0},
    {"city": "Bradford", "ranking": 0},
    {"city": "Brighton", "ranking": 0},
    {"city": "Bristol", "ranking": 0},
    {"city": "Brussels", "ranking": 0},
    {"city": "Budapest", "ranking": 0},
    {"city": "Cambridge, UK", "ranking": 0},
    {"city": "Cardiff", "ranking": 0},
    {"city": "Cheltenham", "ranking": 0},
    {"city": "Chester", "ranking": 0},
    {"city": "Copenhagen", "ranking": 0},
    {"city": "Chester", "ranking": 0},
    {"city": "Copenhagen", "ranking": 0},
    {"city": "Cork", "ranking": 0},
    {"city": "Cologne", "ranking": 0},
    {"city": "Dublin", "ranking": 0},
    {"city": "Dubai", "ranking": 0},
    {"city": "Derby", "ranking": 0},
    {"city": "Dubrovnik", "ranking": 0},
    {"city": "Durham, UK", "ranking": 0},
    {"city": "Edinburgh", "ranking": 0},
    {"city": "Exeter", "ranking": 0},
    {"city": "Eastbourne", "ranking": 0},
    {"city": "Eskdale", "ranking": 0},
    {"city": "Florence", "ranking": 0},
    {"city": "Funchal", "ranking": 0},
    {"city": "Frankfurt", "ranking": 0},
    {"city": "Faro, Portugal", "ranking": 0},
    {"city": "Fethiye", "ranking": 0},
    {"city": "Folkstone", "ranking": 0},
    {"city": "Fresno", "ranking": 0},
    {"city": "Fukuoka", "ranking": 0},
    {"city": "Glasgow", "ranking": 0},
    {"city": "Gothenburg", "ranking": 0},
    {"city": "Galway", "ranking": 0},
    {"city": "Gateshead", "ranking": 0},
    {"city": "Gloucester", "ranking": 0},
    {"city": "Gatwick", "ranking": 0},
    {"city": "Hamburg", "ranking": 0},
    {"city": "Helsinki", "ranking": 0},
    {"city": "Hong Kong Island", "ranking": 0},
    {"city": "Hounslow", "ranking": 0},
    {"city": "Harrogate", "ranking": 0},
    {"city": "Hammamet", "ranking": 0},
    {"city": "Istanbul", "ranking": 0},
    {"city": "Inverness", "ranking": 0},
    {"city": "Ibiza", "ranking": 0},
    {"city": "Jaipur", "ranking": 0},
    {"city": "Jakarta", "ranking": 0},
    {"city": "Jacksonville", "ranking": 0},
    {"city": "Krakow", "ranking": 0},
    {"city": "Kiev", "ranking": 0},
    {"city": "Kidderminster", "ranking": 0},
    {"city": "Kazan", "ranking": 0},
    {"city": "Keswick", "ranking": 0},
    {"city": "Koh Samui", "ranking": 0},
    {"city": "Kos", "ranking": 0},
    {"city": "Kuala Lumpur", "ranking": 0},
    {"city": "London", "ranking": 0},
    {"city": "Las Vegas", "ranking": 0},
    {"city": "Llandudno", "ranking": 0},
    {"city": "Llanelli", "ranking": 0},
    {"city": "Leeds", "ranking": 0},
    {"city": "Lisbon", "ranking": 0},
    {"city": "Liverpool", "ranking": 0},
    {"city": "Leicester", "ranking": 0},
    {"city": "Los Angeles", "ranking": 0},
    {"city": "Manchester", "ranking": 0},
    {"city": "Maidstone", "ranking": 0},
    {"city": "Malaga", "ranking": 0},
    {"city": "Marbella", "ranking": 0},
    {"city": "Marrakech", "ranking": 0},
    {"city": "Malmo", "ranking": 0},
    {"city": "Miami", "ranking": 0},
    {"city": "Milan", "ranking": 0},
    {"city": "Munich", "ranking": 0},
    {"city": "Mumbai", "ranking": 0},
    {"city": "Mykonos", "ranking": 0},
    {"city": "Minsk", "ranking": 0},
    {"city": "Mykonos", "ranking": 0},
    {"city": "New York", "ranking": 0},
    {"city": "Newcastle", "ranking": 0},
    {"city": "Newquay", "ranking": 0},
    {"city": "Newport, UK", "ranking": 0},
    {"city": "New Dehli", "ranking": 0},
    {"city": "Naples, Italy", "ranking": 0},
    {"city": "Nice", "ranking": 0},
    {"city": "Nottingham", "ranking": 0},
    {"city": "Northampton", "ranking": 0},
    {"city": "Norwich", "ranking": 0},
    {"city": "Neath", "ranking": 0},
    {"city": "Oxford", "ranking": 0},
    {"city": "Oslo", "ranking": 0},
    {"city": "Orlando", "ranking": 0},
    {"city": "Paris", "ranking": 0},
    {"city": "Palma De Mallorca", "ranking": 0},
    {"city": "Phuket", "ranking": 0},
    {"city": "Poole", "ranking": 0},
    {"city": "Portsmouth", "ranking": 0},
    {"city": "Plymouth", "ranking": 0},
    {"city": "Prague", "ranking": 0},
    {"city": "Preston", "ranking": 0},
    {"city": "Penrith", "ranking": 0},
    {"city": "Pontypridd", "ranking": 0},
    {"city": "Rome", "ranking": 0},
    {"city": "Reading, UK", "ranking": 0},
    {"city": "Rhodes", "ranking": 0},
    {"city": "Reykjavik", "ranking": 0},
    {"city": "Rio De Janeiro", "ranking": 0},
    {"city": "Scarborough", "ranking": 0},
    {"city": "Shanghai", "ranking": 0},
    {"city": "Sheffield", "ranking": 0},
    {"city": "Singapore", "ranking": 0},
    {"city": "Slough", "ranking": 0},
    {"city": "Sofia", "ranking": 0},
    {"city": "Southampton", "ranking": 0},
    {"city": "Southend-on-sea", "ranking": 0},
    {"city": "Stratford-upon-avon", "ranking": 0},
    {"city": "Stockholm", "ranking": 0},
    {"city": "Swindon", "ranking": 0},
    {"city": "Swansea", "ranking": 0},
    {"city": "Tel Aviv", "ranking": 0},
    {"city": "Tokyo", "ranking": 0},
    {"city": "Torquay", "ranking": 0},
    {"city": "Toronto", "ranking": 0},
    {"city": "Valencia", "ranking": 0},
    {"city": "Venice", "ranking": 0},
    {"city": "Vienna", "ranking": 0},
    {"city": "Vancouver", "ranking": 0},
    {"city": "Warsaw", "ranking": 0},
    {"city": "Windsor", "ranking": 0},
    {"city": "Whitby", "ranking": 0},
    {"city": "Whitstable", "ranking": 0},
    {"city": "Wolverhampton", "ranking": 0},
    {"city": "Winchester", "ranking": 0},
    {"city": "Windermere", "ranking": 0},
    {"city": "York", "ranking": 0}
]

